### ISSUE TITLE
First run error

### ISSUE THREAD

**Issue by steelorbis** [sgoertzen/sonar-break-maven-plugin#12]
Hi Shawn, 

When the project is run the first time, I have the following error: 
``
Caused by: java.io.FileNotFoundException: http://sonarqube.test3.a5f72df0.svc.dockerapp.io:9000/api/resources/index?resource=master:parent&metrics=quality_gate_details
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at com.sgoertzen.sonarbreak.QueryExecutor.fetchSonarStatus(QueryExecutor.java:66)
	at com.sgoertzen.sonarbreak.QueryExecutor.fetchSonarStatusWithRetries(QueryExecutor.java:148)
	at com.sgoertzen.sonarbreak.QueryExecutor.execute(QueryExecutor.java:131)
	at com.sgoertzen.sonarbreak.SonarBreakMojo.execute(SonarBreakMojo.java:54)

Plugin checks every 10s (_SONAR_PROCESSING_WAIT_TIME_) until the set _waitForProcessingSeconds_  expires. However the first results will be available only after they are processed which takes about 1 minute in my case. So the first check throws a FileNotFoundException. 

I think loop should not be interrupted even if the previous checks throws any type of IOException.

**Comment by steelorbis** [comment]
Hi Shawn, 

Would it be possible to fix this issue? 

Thanks.

**Comment by sgoertzen** [comment]
I'm out of the country for two weeks.  I can look at it when I get back or
you are welcome to fix it yourself and I could accept the pull request into
the repo.

**Comment by steelorbis** [comment]
I did.
